version: '3.7'

services:
  mongo:
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: m0ng0#123
    ports:
      - "27017:27017"
    volumes:
      - /home/igor/Documents/db_data:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: teste
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: m0ng0#123
    networks:
      - backend

networks: 
    backend:
      driver: bridge
