version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: m0ng0#123
    ports:
      - "27017:27017"
    volumes:
      - /home/igor/Documents/db_data:/data/db
    networks:
      - backend
  
  api:
    container_name: api
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - 5000:5000
    networks:
      - backend

networks: 
    backend:
      driver: bridge
