version: '3.7'







services:
  mongo:
    env_file:
      - ../config.env
    container_name: mongo
    image: mongo:4.4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ${DB_DATA_PATH}:/data/db
    networks:
      - backend
  
  api:
    container_name: api
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - 5000:5000
    networks:
      - backend

networks: 
    backend:
      driver: bridge
